apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
   traefik.ingress.kubernetes.io/affinity: 'true'
  labels:
    app_name: simple-pipeline-k8s
    resource_level: low
    tier: dev
  name: simple-pipeline-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app_name: simple-pipeline-k8s
      resource_level: low
      tier: dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app_name: simple-pipeline-k8s
        resource_level: low
        tier: dev
    spec:
      containers:
      - env:
        - name: 'VARIAVEIS'
          value: 'DEV'
        image: NOME_DA_IMAGEM
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        name: simple-pipeline-k8s
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 10m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
