type: python
runTests: true
testCommand: python -m pylint --exit-zero app/webserver.py 
deployUponTestSuccess: false
deployToolImage: bash
deployCommand: python2 app/webserver.py
deployEnvironment: dev
#
JOB_NAME: simple_pipeline_k8s
KUBE_METADATA_TIER: dev
KUBE_METADATA_RESOURCE_LEVEL: low
KUBE_DNS_DOMAIN: apps.example.com.br
KUBE_SECRET_DB_PASSWORD: False
KUBE_API_PORT: 3344
KUBE_CONTAINER_COMMAND: 'tail'
KUBE_ENV_FILE_SECRETS_GENERIC_FILE_NAME: daltomate-api-env
KUBE_IMAGE_NAME: simple_pipeline_k8s
KUBE_HEALTHCHECK: True
KUBE_HEALTHCHECK_PATH: /
