type: python
runTests: true
testCommand: python -m pylint --exit-zero app/webserver.py 
deployUponTestSuccess: false
deployToolImage: bash
deployCommand: python2 app/webserver.py
deployEnvironment: dev